# Web services and nginx
version: '3.8'

services:
  rpg-web:
    image: ghcr.io/kirkdiggler/rpg-dnd5e-web:latest
    container_name: rpg-web
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - rpg-api
    networks:
      - rpg-network

  nginx:
    image: nginx:alpine
    container_name: rpg-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - rpg-api
      - rpg-web
      - envoy
    networks:
      - rpg-network