version: '3.8'

# Optional: Standalone certbot service
# This can be used instead of the integrated nginx/certbot approach
# To use: docker-compose -f docker-compose.prod.yml -f docker-compose.certbot.yml up -d

services:
  certbot:
    image: certbot/certbot:latest
    container_name: rpg-certbot
    restart: unless-stopped
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
  nginx:
    # Override the nginx service to use the standard image instead of custom build
    image: nginx:alpine
    build: none
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - certbot-conf:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"